version: '3.8'

services:
  # Orders Database
  orders-db:
    image: postgres:15-bookworm
    container_name: pifko-orders-db
    environment:
      - POSTGRES_DB=brewery_orders
      - POSTGRES_USER=pifko_user
      - POSTGRES_PASSWORD=pifko_password123
    ports:
      - "8081:5432"
    volumes:
      - orders_data:/var/lib/postgresql/data
    networks:
      - pifko-network

  # Brewery Operations Database
  brewery-db:
    image: postgres:15-bookworm
    container_name: pifko-brewery-db
    environment:
      - POSTGRES_DB=brewery_operations
      - POSTGRES_USER=pifko_user
      - POSTGRES_PASSWORD=pifko_password123
    ports:
      - "8082:5432"
    volumes:
      - brewery_data:/var/lib/postgresql/data
    networks:
      - pifko-network

  # Storage Database
  storage-db:
    image: postgres:15-bookworm
    container_name: pifko-storage-db
    environment:
      - POSTGRES_DB=brewery_storage
      - POSTGRES_USER=pifko_user
      - POSTGRES_PASSWORD=pifko_password123
    ports:
      - "8083:5432"
    volumes:
      - storage_data:/var/lib/postgresql/data
    networks:
      - pifko-network

  # Orders Service
  orders-service:
    build:
      context: .
      dockerfile: ./src/Pifko/services/orders_service/Dockerfile
    container_name: pifko-orders-service
    environment:
      - DATABASE_URL=postgresql://pifko_user:pifko_password123@orders-db:5432/brewery_orders
  
      - BREWERY_SERVICE_URL=http://brewery-service:8002
      - STORAGE_SERVICE_URL=http://storage-service:8003
    ports:
      - "8001:8001"
    depends_on:
      - orders-db
    networks:
      - pifko-network

  # Brewery Operations Service
  brewery-service:
    build:
      context: .
      dockerfile: ./src/Pifko/services/brewery_service/Dockerfile
    container_name: pifko-brewery-service
    environment:
      - DATABASE_URL=postgresql://pifko_user:pifko_password123@brewery-db:5432/brewery_operations
      - ORDERS_SERVICE_URL=http://orders-service:8001
      - STORAGE_SERVICE_URL=http://storage-service:8003
    ports:
      - "8002:8002"
    depends_on:
      - brewery-db
      - storage-service
    networks:
      - pifko-network

  # Storage Service
  storage-service:
    build:
      context: .
      dockerfile: ./src/Pifko/services/storage_service/Dockerfile
    container_name: pifko-storage-service
    environment:
      - DATABASE_URL=postgresql://pifko_user:pifko_password123@storage-db:5432/brewery_storage
      - ORDERS_SERVICE_URL=http://orders-service:8001
      - BREWERY_SERVICE_URL=http://brewery-service:8002
    ports:
      - "8003:8003"
    depends_on:
      - storage-db
    networks:
      - pifko-network

networks:
  pifko-network:
    driver: bridge
    name: pifko-network

volumes:
  orders_data:
    name: pifko_orders_data
  brewery_data:
    name: pifko_brewery_data
  storage_data:
    name: pifko_storage_data